[shell]
args = ['--login']
program = "/usr/bin/bash"

[font]
size = 12.0

[font.normal]
family = "hack"

[colors.normal]
black = '#282828'
red = '#cc241d'
green = '#98971a'
yellow = '#d79921'
blue = '#458588'
magenta = '#b16286'
cyan = '#689d6a'
white = '#a89984'


[colors.primary]
background = '#282828'
foreground = '#ebdbb2'
